### ISSUE TITLE
shuffle breaks longitudinal data

### ISSUE THREAD

**Issue by lacava** [lacava/feat#237]
i'm running a controlled experiment with simulation data and it is clear that `shuffle=True` is breaking the longitudinal data's alignment with samples in X. We need to check what is going on asap

**Comment by tilakhere** [comment]
@lacava The issue is in reorder_longitudinal() in io.cc. I notice we initially implemented it using the first answer given [here](https://stackoverflow.com/questions/838384/reorder-vector-using-a-vector-of-indices) which seemed incorrect while we tested it. Later while working on the longitudinal python api it was implemented again (commit https://github.com/lacava/feat/commit/44bb34f4bf96444107943ed698dac1cc1b443484#diff-16b21622fbae2aaa5a74b2eb5bdce9f3) which is the current version but that is also not giving the correct results.

Using the same stackoverflow link mentioned above I implemented it using the second answer given there which seems to order the data correctly. (not sure though have checked it on small datasets)

I have made a reorder_long and pushed the temporary changes via commit https://github.com/lacava/feat/commit/49e427fd32cfc422b6caa97f345ace2b6eca050f. Could you please check it at your end to and verify if its fixed or not.
