### ISSUE TITLE
Stack class 

### ISSUE THREAD

**Issue by lacava** [lacava/feat#49]
write a generic stack class that can be used in place of type-specific stacks and handle multi-typed operators.

it should look something handle pushing and popping with single commands (wrapping the vector `back()` and `pop_back()`) and should handle types internally, e.g. 

```
Stack stack;
stack['f'].push(stack['b'].pop().select(stack['f'].pop(), stack['f'].pop()));
```
would represent and if-then-else operation.

**Comment by tilakhere** [comment]
commit https://github.com/lacava/feat/commit/40f28e4dee57dc73ed7c2c7dc3ec7af6ff5b205d

Since overloading operator[] could not guarantee different return types hence instead of `stack['f']` or `stack['b']`, `stack.f` and `stack.b` are supported.

**Comment by lacava** [comment]
Some questions and comments...

 - Can you do `ArrayXb x = stack.pop()` and have it return an element from the correct stack?
- It would be nice to wrap the stack/node check into a Stack class method. so that 
`(stack.f.size() >= n->arity['f'] && stack.b.size() >= n->arity['b'])`
would become something like `stack.check(n)` and you could define
`bool Stack::check(Node & n) { return stack.f.size() >= n->arity['f'] && stack.b.size() >= n->arity['b'];}`
then we could update the check function in one place as we add /change the stacks. 
 - the stack name "l" is not nice .. it's hard to read lower case l names. please rename it to 'z' or 'long'.

**Comment by tilakhere** [comment]
@lacava 

commit https://github.com/lacava/feat/commit/409c0dd62d0b4a1e8513a4272c8aef948968067d
- `ArrayXb x = stack.pop()` cannot be implemented to return element from correct stack as we need to specify return type in pop() function definition which cannot be generic. Thats why implemented `stack.f`, `stack.b` and `stack.z`. Let me know if you can think of a way this can be improved.

- `stack.check(arity)` method implemented. Instead of using the whole `Node&` have used `node->arity` data member reference as parameter as then stack class would depend on node class and node already is dependent on stack class which would create a cyclic dependency. 

- replaced `stack.l` with `stack.z` everywhere
- simplified nodes' `evaluate()` and `eval_eqn()`

**Comment by lacava** [comment]
PR #94 merges this into master
