### ISSUE TITLE
merge test cmake with feat cmake

### ISSUE THREAD

**Issue by lacava** [lacava/feat#83]
right now we separately install google tests and separately build tests with a different cmake file. we should integrate these routines into the main CMake process for feat. 

see [the googletest guidelines](https://github.com/google/googletest/blob/master/googletest/README.md#incorporating-into-an-existing-cmake-project) for incorporating googletest into an existing project. 

the idea is to have a command line argument specifying whether to make the tests (e.g. `make test`) and have that trigger a separate sub-build routine. there could also be a flag in cmake to specify whether to test build files at all.

**Comment by tilakhere** [comment]
removed tests/CMakeLists.txt and combined tests building in feat cmake. commit https://github.com/lacava/feat/commit/78827886115b71cfaca1ea1e371cea118a123243

Tests can now be built using command make tests.

Couldn't use "test" as the executable name as cmake didnt allow that due to a reserved keyword, hence executable name is "tests"

**Comment by tilakhere** [comment]
@lacava This was fixed during our last meeting

commits https://github.com/lacava/feat/commit/7da3501571bf99a2e8c4bf6e6995d11160d60f47 and https://github.com/lacava/feat/commit/c7ad016c12ac3775f82694f6c58845971909069e

Need to merge this pull request https://github.com/lacava/feat/pull/87
